-- ============================================================================
-- DEPRECATED: This trigger-based approach has been replaced
-- ============================================================================
-- Lead notifications are now created atomically with leads using the
-- create_lead_with_notification() RPC function.
--
-- This file is kept for reference only and should not be used.
--
-- Previous approach (DEPRECATED):
-- - Trigger would fire after INSERT on leads table
-- - Trigger would call edge function to send notification
-- - This was unreliable and notifications were being missed
--
-- New approach (USE THIS):
-- - Call create_lead_with_notification(p_request_id, p_pro_id) instead of INSERT
-- - This creates both lead and notification atomically
-- - No triggers needed
-- - 100% reliable
--
-- See: create-lead-with-notification-rpc.sql for the new implementation
