// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxraykdmlshcntqjumpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4cmF5a2RtbHNoY250cWp1bXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTQyMjIsImV4cCI6MjA3NDMzMDIyMn0.o0ytcar3x-kBbfv23Sb3hUnCWMR9H-JyyUYwu4w3GtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});